// src/components/team/TeamMemberCard.tsx
import { TeamMember } from "@prisma/client";
import CubyxImage from "../CubyxImage";

const TeamMemberCard = ({ member }: { member: TeamMember }) => {
  return (
    <div className="flex w-60 items-center gap-2 rounded-2xl border border-text-primary p-2 transition-all hover:translate-x-4 hover:cursor-pointer dark:border-text-primary-dark">
      <CubyxImage
        src={`/api/profilePicture/${member.id}`}
        alt={`${member.username} profile picture`}
        className="h-10 w-10"
      />
      <h3 className="text-xl">{member.username}</h3>
    </div>
  );
};

export default TeamMemberCard;

// src/components/Team/TeamMemberCard.svelte
<script lang="ts">
	import type { TeamMember } from '@prisma/client';
	import { Icon } from 'svelte-awesome';
	import { faDiscord } from '@fortawesome/free-brands-svg-icons/faDiscord';

	export let teamMember: Omit<TeamMember, 'avatar'>;
</script>

<div class="card rounded-box bg-secondary">
	<figure>
		<img
			src="/api/teamMember/avatar/{teamMember.id}"
			alt="Avatar von {teamMember.name}"
			class="w-full"
		/>
	</figure>
	<div class="card-body">
		<h2 class="card-title w-full break-all">{teamMember.name}</h2>
		<span class="flex items-center gap-2 text-neutral">
			<Icon data={faDiscord} />
			<p class="w-full text-sm">{teamMember.discord}</p>
		</span>
	</div>
</div>
